version: '3'
services:
  pg:
    container_name: pg
    image: 'postgres'
    env_file:
      - database.env
    volumes:
      - pg-data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
  es:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
volumes:
  pg-data: 
  elastic-data:
